apiVersion: v1
kind: PersistentVolume
metadata:
  name: httpd-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/httpd"
  capacity:
    storage: 10Gi
