apiVersion: v1
kind: PersistentVolume
metadata:
  name: httpd-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/C/Users/Public/Documents/httpd"
  capacity:
    storage: 10Gi
