apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-11-03T04:15:16Z"
  labels:
    app: httpd
  name: httpd
  namespace: default
  resourceVersion: "844919"
  uid: 6f48c143-3a8b-4c16-909d-486a48f18b61
spec:
  clusterIP: 10.97.176.175
  clusterIPs:
  - 10.97.176.175
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31715
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
