apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wispr
  name: wispr
  namespace: default
spec:
  selector:
    matchLabels:
      app: wispr
  template:
    metadata:
      labels:
        app: wispr
    spec:
      containers:
      - image: dogkeeper886/wispr:0.57
        imagePullPolicy: IfNotPresent
        name: wispr
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi        
        env:
        - name: API_KEY
          value: MY_API_KEY      