apiVersion: v1
kind: Service
metadata:
  labels:
    app: wispr
  name: wispr
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  - port: 8443
    protocol: TCP
    name: https
  selector:
    app: wispr
  type: NodePort
