apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wispr
  name: wispr
  namespace: default
spec:
  selector:
    matchLabels:
      app: wispr
  template:
    metadata:
      labels:
        app: wispr
    spec:
      containers:
      - image: dogkeeper886/wispr:0.71
        imagePullPolicy: IfNotPresent
        name: wispr
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi        
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: wispr
              key: API_KEY
              optional: false
        - name: TLS_CERT
          valueFrom:
            secretKeyRef:
              name: my-tls-secret
              key: tls.crt
              optional: false
        - name: TLS_KEY
          valueFrom:
            secretKeyRef:
              name: my-tls-secret
              key: tls.key
              optional: false
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"          